### ISSUE TITLE
Replacing markdown syntax for quoting code in all files

### ISSUE THREAD

**Issue by Matthes-Kdr** [Matthes-Kdr/code-documentation-generator#19]
Since I was not aware that quoting code will work by using just `this` (\`this\`), I have used ```this``` (\`\`\`this\`\`\`) therefore consequently which is much less readeble.

I don't know wheather it makes any difference regarding the output files / rendering. I don't think so, but with time this should be sorted out to get readeble stuff.

relevant files (just a quick search - I didn't check it all!):
- code_documenter.py
- templates\prozedur_dev.md:
- templates\prozedur.md:
- templates\sec_toc_subs.md:

**Comment by Matthes-Kdr** [comment]
@Tobiloba014  :  Thanks for your contribution! But I am sorry, I think I should have been more precise:

It seems as you mainly corrected the HTML output -files. But these files can actually be removed from this repository as they could be generated anytimes again - I had uploaded them for some example files.  One additional exception from that is the file "html/code_ducumenter.html". This is just the output of the usage of pdoc for this code_documenter.py module, so it is only documentation and does not have to be changed manually.

The issue has to been solved within the relevant code which is used for the generation of the documentation. This happens mainly in two places:
- in the templates, see directory "templates/" (and there: just focus on the md-files and just ignore the few html files, they are only to have a look at the potential output, they are not used for anything)
- in the Python module code_documenter.py , when markdown code is written to a file (or before writing to it, when markdown syntax is been stored in variables of classes or objects...)

I hope this makes things a bit more clearly. Maybe I should add an overview about the data structure and the used files..

**Comment by Matthes-Kdr** [comment]
The templates have been modified now.
(I didn't correct the old example output md + html files..)

**Comment by Tobiloba014** [comment]
That's good
